# Generated by Django 5.2.11 on 2026-02-13 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_logic', models.IntegerField(default=0)),
                ('xp_systems', models.IntegerField(default=0)),
                ('xp_narrative', models.IntegerField(default=0)),
                ('xp_spatial', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('streak_count', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
