# Generated by Django 5.2.11 on 2026-02-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quizsession_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='division',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(default='Default School', max_length=100),
        ),
    ]
