# Generated by Django 5.2.11 on 2026-02-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customuser_division_customuser_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roll_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
