# Generated by Django 5.2.11 on 2026-02-16 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_roll_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
