# Generated by Django 5.2.11 on 2026-02-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customuser_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='chat_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.chatsession'),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz_type',
            field=models.CharField(choices=[('chat', 'Chat Based'), ('daily', 'Daily Weak Dimension'), ('gk', 'General Awareness')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='dimension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
