# Generated by Django 5.2.11 on 2026-03-12 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_quizquestion_explanation_quizsession_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='mastery_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizsession',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_quiz_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TopicMastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=200)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('mastery_percentage', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_masteries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Topic Masteries',
                'unique_together': {('user', 'subject', 'topic')},
            },
        ),
    ]
